name = "vfc-omr-fe"
compatibility_date = "2023-10-30"

[build]
command = "yarn build"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"
YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
