const MainRoutes = {
  path: "/",
  meta: {
    requiresAuth: true,
  },
  // redirect: '/dashboard',
  component: () => import("@/layouts/dashboard/DashboardLayout.vue"),
  children: [
    {
      name: "Dashboard",
      path: "",
      component: () => import("@/views/dashboards/Dashboard.vue"),
      meta: { title: "mainMenu.myDashboard" },
    },
    {
      name: "Test",
      path: "test/test",
      component: () => import("@/views/test/Test.vue"),
      meta: { title: "pageTitle.test" },
    },
    {
      name: "Report Form",
      path: "test/report-form",
      component: () => import("@/views/test/ReportForm.vue"),
      meta: { title: "pageTitle.reportForm" },
    },
    {
      name: "ChurchAdd",
      path: "/churches/add",
      component: () => import("@/views/churches/AddChurch.vue"),
      meta: { title: "church.addTitle" },
    },
    {
      name: "ChurchAddWithNewPastor",
      path: "/churches/add-with-new-pastor",
      component: () => import("@/views/churches/AddChurchWithNewPastor.vue"),
      meta: { title: "church.addWithNewUserTitle" },
    },
    {
      name: "ChurchEdit",
      path: "/churches/:id/edit",
      component: () => import("@/views/churches/EditChurch.vue"),
      meta: { title: "church.editTitle" },
    },
    {
      name: "ChurchClone",
      path: "/churches/:id/clone",
      component: () => import("@/views/churches/CloneChurch.vue"),
      meta: { title: "church.cloneTitle" },
    },
    {
      name: "ChurchDisabledList",
      path: "/churches/disabled-list",
      component: () => import("@/views/churches/ListDisabledChurch.vue"),
      meta: { title: "church.listDisabledTitle" },
    },
    {
      name: "ChurchList",
      path: "/churches",
      component: () => import("@/views/churches/ListChurch.vue"),
      meta: { title: "church.listTitle" },
    },
    {
      name: "ChurchDetail",
      path: "/churches/:id",
      component: () => import("@/views/churches/DetailChurch.vue"),
      meta: { title: "pageTitle.churchDetail" },
    },
    {
      name: "MonthlyDataAdd",
      path: "/churches/:id/monthly-data/add",
      component: () => import("@/views/monthly-data/Add.vue"),
      meta: { title: "dashboardMenu.monthlyData" },
    },
    {
      name: "UserAdd",
      path: "users/add",
      component: () => import("@/views/users/AddUser.vue"),
      meta: { title: "user.addTitle" },
    },
    {
      name: "UserEdit",
      path: "users/:id/edit",
      component: () => import("@/views/users/EditUser.vue"),
      meta: { title: "user.editTitle" },
    },
    {
      name: "UserList",
      path: "users",
      component: () => import("@/views/users/ListUser.vue"),
      meta: { title: "user.listTitle" },
    },
    {
      name: "UserDetail",
      path: "users/:id",
      component: () => import("@/views/users/Detail.vue"),
      meta: { title: "pageTitle.userDetail" },
    },
    {
      name: "UserOverseerList",
      path: "users/overseers",
      component: () => import("@/views/users/ListOverseerUser.vue"),
      meta: { title: "user.listOverseerTitle" },
    },
    {
      name: "WorshipServiceList",
      path: "churches/:churchId/services",
      component: () => import("@/views/worship-services/ListWorshipService.vue"),
      meta: { title: "dashboardMenu.worshipServices" },
    },
    {
      name: "WorshipServiceAdd",
      path: "churches/:churchId/services/add",
      component: () => import("@/views/worship-services/AddWorshipService.vue"),
      meta: { title: "worshipService.addTitle" },
    },
    {
      name: "WorshipServiceEdit",
      path: "churches/:churchId/services/:id/edit",
      component: () => import("@/views/worship-services/EditWorshipService.vue"),
      meta: { title: "worshipService.editTitle" },
    },
    {
      name: "ChurchNetworkList",
      path: "church-networks",
      component: () => import("@/views/church-networks/ListChurchNetwork.vue"),
      meta: { title: "churchNetwork.listTitle" },
    },
    {
      name: "ChurchNetworkAdd",
      path: "church-networks/add",
      component: () => import("@/views/church-networks/AddChurchNetwork.vue"),
      meta: { title: "churchNetwork.addTitle" },
    },
    {
      name: "ChurchNetworkEdit",
      path: "church-networks/:id/edit",
      component: () => import("@/views/church-networks/EditChurchNetwork.vue"),
      meta: { title: "churchNetwork.editTitle" },
    },
    {
      name: "ChurchTypeList",
      path: "church-types",
      component: () => import("@/views/church-types/ListChurchType.vue"),
      meta: { title: "churchType.listTitle" },
    },
    {
      name: "ChurchTypeAdd",
      path: "church-types/add",
      component: () => import("@/views/church-types/AddChurchType.vue"),
      meta: { title: "churchType.addTitle" },
    },
    {
      name: "ChurchTypeEdit",
      path: "church-types/:id/edit",
      component: () => import("@/views/church-types/EditChurchType.vue"),
      meta: { title: "churchType.editTitle" },
    },
    {
      name: "LanguageList",
      path: "languages",
      component: () => import("@/views/languages/ListLanguage.vue"),
      meta: { title: "language.listTitle" },
    },
    {
      name: "LanguageAdd",
      path: "languages/add",
      component: () => import("@/views/languages/AddLanguage.vue"),
      meta: { title: "language.addTitle" },
    },
    {
      name: "LanguageEdit",
      path: "languages/:id/edit",
      component: () => import("@/views/languages/EditLanguage.vue"),
      meta: { title: "language.editTitle" },
    },
    {
      name: "CountryList",
      path: "countries",
      component: () => import("@/views/countries/ListCountry.vue"),
      meta: { title: "country.listTitle" },
    },
    {
      name: "CountryAdd",
      path: "countries/add",
      component: () => import("@/views/countries/AddCountry.vue"),
      meta: { title: "country.addTitle" },
    },
    {
      name: "CountryEdit",
      path: "countries/:id/edit",
      component: () => import("@/views/countries/EditCountry.vue"),
      meta: { title: "country.editTitle" },
    },
    {
      name: "LanguageRegionsList",
      path: "language-regions",
      component: () => import("@/views/language-regions/List.vue"),
      meta: { title: "languageRegions.listTitle" },
    },
    {
      name: "LanguageRegionsAdd",
      path: "language-regions/add",
      component: () => import("@/views/language-regions/Add.vue"),
      meta: { title: "languageRegions.addTitle" },
    },
    {
      name: "LanguageRegionsEdit",
      path: "language-regions/:id/edit",
      component: () => import("@/views/language-regions/Edit.vue"),
      meta: { title: "languageRegions.editTitle" },
    },
    {
      name: "GeographicalRegionsList",
      path: "geographical-regions",
      component: () => import("@/views/geographical-regions/List.vue"),
      meta: { title: "geographicalRegions.listTitle" },
    },
    {
      name: "GeographicalRegionsAdd",
      path: "geographical-regions/add",
      component: () => import("@/views/geographical-regions/Add.vue"),
      meta: { title: "geographicalRegions.addTitle" },
    },
    {
      name: "GeographicalRegionsEdit",
      path: "geographical-regions/:id/edit",
      component: () => import("@/views/geographical-regions/Edit.vue"),
      meta: { title: "geographicalRegions.editTitle" },
    },
    {
      name: "ChurchRegionsList",
      path: "church-regions",
      component: () => import("@/views/church-regions/List.vue"),
      meta: { title: "churchRegions.listTitle" },
    },
    {
      name: "ChurchRegionsAdd",
      path: "church-regions/add",
      component: () => import("@/views/church-regions/Add.vue"),
      meta: { title: "churchRegions.addTitle" },
    },
    {
      name: "ChurchRegionsEdit",
      path: "church-regions/:id/edit",
      component: () => import("@/views/church-regions/Edit.vue"),
      meta: { title: "churchRegions.editTitle" },
    },
    {
      name: "PlantingProjectionRedirect",
      path: "planting-projections",
      component: () => import("@/views/planting-projections/Redirect.vue"),
      meta: { permissions: ["church-planting.read"], title: "churchPlantingProjection.dashboardTitle" },
    },
    {
      name: "PlantingProjectionAddRedirect",
      path: "planting-projections/add",
      component: () => import("@/views/planting-projections/AddRedirect.vue"),
      meta: { permissions: ["church-planting.create"], title: "churchPlantingProjection.addTitle" },
    },
    {
      name: "PlantingProjectionPrintSimple",
      path: "planting-projections/print",
      component: () => import("@/views/planting-projections/PrintSimple.vue"),
      meta: { permissions: ["church-planting.print"], title: "churchPlantingProjection.printTitleSimple" },
    },
    {
      name: "PlantingProjectionPrintPreview",
      path: "planting-projections/print/preview",
      component: () => import("@/views/planting-projections/PrintPreviewSteps.vue"),
      meta: { permissions: ["church-planting.print-preview"], title: "churchPlantingProjection.printTitlePreview" },
    },
    {
      name: "PlantingProjectionList",
      path: "churches/:churchId/planting-projections",
      component: () => import("@/views/planting-projections/List.vue"),
      meta: { permissions: ["church-planting.read"], title: "churchPlantingProjection.dashboardTitle" },
    },
    {
      name: "PlantingProjectionAdd",
      path: "churches/:churchId/planting-projections/add",
      component: () => import("@/views/planting-projections/Add.vue"),
      meta: { permissions: ["church-planting.create"], title: "churchPlantingProjection.addTitle" },
    },
    {
      name: "PlantingProjectionEdit",
      path: "churches/:churchId/planting-projections/:id/edit",
      component: () => import("@/views/planting-projections/Edit.vue"),
      meta: { permissions: ["church-planting.read"], title: "churchPlantingProjection.editTitle" },
    },
    {
      name: "PlantingProjectionEditSteps",
      path: "churches/:churchId/planting-projections/:id/edit-steps",
      component: () => import("@/views/planting-projections/EditSteps.vue"),
      meta: { permissions: ["church-planting.read"], title: "churchPlantingProjection.editStepsPageTitle" },
    },
    {
      name: "VisitsAdd",
      path: "visits/add",
      component: () => import("@/views/visits/Add.vue"),
      meta: { title: "visitsAdd.title" },
    },
    {
      name: "SupportSend",
      path: "support",
      component: () => import("@/views/support/Send.vue"),
      meta: { title: "support.title" },
    },
    {
      name: "FaqList",
      path: "faqs",
      component: () => import("@/views/faqs/ListFaq.vue"),
      meta: { permissions: ["faq.read"], title: "faq.listTitle" },
    },
    {
      name: "FaqSearch",
      path: "faqs/search",
      component: () => import("@/views/faqs/SearchFaq.vue"),
      meta: { permissions: ["faq.read"], title: "faq.searchTitle" },
    },
    {
      name: "FaqAdd",
      path: "faqs/add",
      component: () => import("@/views/faqs/AddFaq.vue"),
      meta: { permissions: ["faq.create"], title: "faq.addTitle" },
    },
    {
      name: "FaqEdit",
      path: "faqs/:id/edit",
      component: () => import("@/views/faqs/EditFaq.vue"),
      meta: { permissions: ["faq.update"], title: "faq.editTitle" },
    },
    {
      name: "FaqDetail",
      path: "faqs/:id",
      component: () => import("@/views/faqs/DetailFaq.vue"),
      meta: { permissions: ["faq.read"], title: "faq.detailTitle" },
    },
    // {
    //   name: 'MonthlyDataAdd',
    //   path: 'monthly-data/add',
    //   component: () => import('@/views/monthly-data/Add.vue')
    // }
  ],
};

export default MainRoutes;
