import {
  mdiCheckboxMarkedCircleOutline,
  mdiMagnify,
  mdiMenuDown,
  mdiChevronUp,
  mdiChevronDown,
  mdiReply,
  mdiCircleOutline,
  mdiBlockHelper,
  mdiCloseCircle,
  mdiAlertOutline,
  mdiHelpCircleOutline,
  mdiEmoticonHappy,
  mdiEmoticonHappyOutline,
  mdiHeart,
  mdiHeartOutline,
  mdiHeartHalf,
  mdiPencil,
  mdiInformationOutline,
  mdiDelete,
  mdiContentCopy,
  mdiArrowLeft,
  mdiAccountGroup,
  mdiChartLine,
  mdiTrendingUp,
  mdiChurchOutline,
  mdiCurrencyUsd,
  mdiSwapHorizontal,
  mdiPlusCircleOutline,
  mdiSquare,
  mdiSquareEditOutline,
  mdiChartBar,
  mdiLogout
} from '@mdi/js';
import { mdi } from 'vuetify/iconsets/mdi-svg';

export const icons = {
  checkboxMarkedCircleOutline: mdiCheckboxMarkedCircleOutline,
  magnify: mdiMagnify,
  menuDown: mdiMenuDown,
  chevronUp: mdiChevronUp,
  chevronDown: mdiChevronDown,
  reply: mdiReply,
  circleOutline: mdiCircleOutline,
  blockHelper: mdiBlockHelper,
  closeCircle: mdiCloseCircle,
  alertOutline: mdiAlertOutline,
  helpCircleOutline: mdiHelpCircleOutline,
  emoticonHappy: mdiEmoticonHappy,
  emoticonHappyOutline: mdiEmoticonHappyOutline,
  heart: mdiHeart,
  heartOutline: mdiHeartOutline,
  heartHalf: mdiHeartHalf,
  pencil: mdiPencil,
  informationOutline: mdiInformationOutline,
  delete: mdiDelete,
  copy: mdiContentCopy,
  arrowLeft: mdiArrowLeft,

  edit: mdiSquareEditOutline,
  chartBar: mdiChartBar,

  accountGroup: mdiAccountGroup,
  chartLine: mdiChartLine,
  trendingUp: mdiTrendingUp,
  church: mdiChurchOutline,
  currencyUsd: mdiCurrencyUsd,

  swapHorizontal: mdiSwapHorizontal,
  plusCircleOutline: mdiPlusCircleOutline,
  logout: mdiLogout
};
